export const cuisineEmojiMapping = {
    "italian": "🍕",
    "pizza": "🍕",
    "chinese": "🥡",
    "japanese": "🍣",
    "korean": "🍲",
    "indian": "🍛",
    "mexican": "🌮",
    "american": "🍔",
    "french": "🥐",
    "thai": "🍜",
    "greek": "🥙",
    "spanish": "🥘",
    "vietnamese": "🍜",
    "burger": "🍔",
    "sushi": "🍣",
    "barbecue": "🍖",
    "seafood": "🦞",
    "steakhouse": "🥩",
    "dessert": "🍰",
    "vegetarian": "🥗",
    "vegan": "🌱",
    "turkish": "🍢",
    "middle eastern": "🥙",
    "arabic": "🥙",
    "mediterranean": "🥙",
    "ice_cream": "🍨",
    "asian": "🥢",    
    "breakfast": "🍳",
    "cajun": "🌶️",
    "cookie": "🍪",
    "fish": "🐟",
    "noodle": "🍜",
    "pasta": "🍝",
    "pub": "🍺",
    "ramen": "🍜",
    "sandwich": "🥪",
    "sandwhich": "🥪", // covers common misspelling
    "steak_house": "🥩"
};

// Example using require (assuming images are stored in ../pictures/cuisine/)
// You can also use import statements if you prefer.
export const cuisineImageMapping = {
    "italian": require('./pictures/cuisine/italian.jpg'),
    "pizza": require('./pictures/cuisine/pizza.jpg'),
    "chinese": require('./pictures/cuisine/chinese.jpg'),
    "japanese": require('./pictures/cuisine/japanese.jpg'),
    "korean": require('./pictures/cuisine/korean.jpg'),
    "indian": require('./pictures/cuisine/indian.jpg'),
    "mexican": require('./pictures/cuisine/mexican.jpg'),
    "american": require('./pictures/cuisine/american.jpg'),
    "french": require('./pictures/cuisine/french.jpg'),
    "thai": require('./pictures/cuisine/thai.jpg'),
    "greek": require('./pictures/cuisine/greek.jpg'),
    "spanish": require('./pictures/cuisine/spanish.jpg'),
    "vietnamese": require('./pictures/cuisine/vietnamese.jpg'),
    "burger": require('./pictures/cuisine/burger.jpg'),
    "sushi": require('./pictures/cuisine/sushi.jpg'),
    "barbecue": require('./pictures/cuisine/barbecue.jpg'),
    "seafood": require('./pictures/cuisine/seafood.jpg'),
    "steakhouse": require('./pictures/cuisine/steakhouse.jpg'),
    "dessert": require('./pictures/cuisine/dessert.jpg'),
    "vegetarian": require('./pictures/cuisine/vegetarian.jpg'),
    "vegan": require('./pictures/cuisine/vegetarian.jpg'),
    "turkish": require('./pictures/cuisine/turkish.jpg'),
    "middle eastern": require('./pictures/cuisine/middle_eastern.jpg'),
    "arabic": require('./pictures/cuisine/arabic.jpg'),
    "mediterranean": require('./pictures/cuisine/mediterranean.jpg'),
    "ice_cream": require('./pictures/cuisine/ice_cream.jpg'),
    "asian": require('./pictures/cuisine/asian.jpg'),
    "breakfast": require('./pictures/cuisine/breakfast.jpg'),
    "cajun": require('./pictures/cuisine/cajun.jpg'),
    "cookie": require('./pictures/cuisine/cookie.jpg'),
    "fish": require('./pictures/cuisine/fish.jpg'),
    "noodle": require('./pictures/cuisine/noodle.jpg'),
    "pasta": require('./pictures/cuisine/pasta.jpg'),
    "pub": require('./pictures/cuisine/pub.jpg'),
    "ramen": require('./pictures/cuisine/ramen.jpg'),
    "sandwich": require('./pictures/cuisine/sandwhich.jpg'),
    "sandwhich": require('./pictures/cuisine/sandwhich.jpg'), // covers common misspelling
    "steak_house": require('./pictures/cuisine/steakhouse.jpg')
};